<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="P_Clock" Id="{3607f292-5366-4b7c-810f-569374c051f5}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM P_Clock
VAR
	
	fbClock : FB_Clock;
	fbMotionClock : FB_Clock;
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
fbClock(
	bStartEnable := G_HMI.bstepp_button,
	
	fTime => G_OPC.fTime
);

fbMotionClock(
	bStartEnable := G_Enables.bSineMotion AND G_Inputs.bEnableButton AND G_Enables.bAuto, // AND G_HMI.bstepp_button AND G_Enables.bHoldButton,
	
	fTime => G_OPC.fMotionTime
);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>