<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="MAIN" Id="{73114a79-e8e7-4c77-9271-864ce29939b0}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	bTemp : BOOL;
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
// P_Filtering();
// P_DanielFiltering();
// P_Inputs();
P_Clock();
P_HMI();
P_DeadBand();
P_FeedForward();
P_PID();
P_Convetions();
P_Control();
P_Motion();
P_Output();
P_Truck();
P_FlowControl();

// Test Programs
//P_SineTest();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>