<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="MAIN" Id="{73114a79-e8e7-4c77-9271-864ce29939b0}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	bTemp : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[P_Filtering();
P_DanielFiltering();
//P_Modes();
P_RunClock();
P_HMI();
P_Inputs();
P_Output();
P_FeedForward();
P_PID();
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>