<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="P_RunClock" Id="{3607f292-5366-4b7c-810f-569374c051f5}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM P_RunClock
VAR
	fbClock : FB_Clock;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
fbClock(
	bStartEnable := G_Enables.bTest,
	fTimeStep := G_Parameters.fTimeStep,
	
	fTime => G_OPC.fTime
);
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>