<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_Button_1" Id="{8bc74369-b140-45ba-9250-a27cb5ef27e3}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Button_1
VAR_INPUT
	bButtonPress : BOOL;
END_VAR
VAR_OUTPUT
	nCounter: INT;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>