<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_Normalize" Id="{1cb17eff-b342-48b7-ab9a-2d7d641deba9}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Normalize
VAR_INPUT
	nRawInput 			: INT;
	fMaxValue 			: LREAL;
END_VAR
VAR_OUTPUT
	fNormalizedInput 	: LREAL;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fNormalizedInput := (fMaxValue	* INT_TO_LREAL(nRawInput)) / 32767.0;

fNormalizedInput := LIMIT(0, fNormalizedInput, fMaxValue);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>